.TH waynew 7 "2021" Personal "Wayne Werner"
.SH NAME
Wayne Werner
.SH PRONOUNS
He/Him/They
.SH DESCRIPTION
.I "All human beings have worth, simply by virtue of being human beings." - Wayne

A human being intensely protective of his time, so it can be given generously. A lover of all things command-line.
.SH OPTIONS
.SS email
Send me an email. This is the most surefire (though potentially high latency) way to contact me. I'm a fan of VSRE emails.
.SS RSS
Both my gopher and web page offer an RSS (Well, Atom really) feed.
.SS gopher
Gopher is an insanely simple protocol, probably my favorite. Pull option.
.SS website
HTTP(s) protocol, also a pull option.
.SH DIAGNOSTICS
.SS "Q: I didn't receive a response, what should I do?"
It's possible that I'm busy helping other people, or perhaps I'm taking a vacation. If it's not an emergency, wait a while. Otherwise, try pinging me again.
.SS "Q: I seem to have offended you, what can I do?"
I'm fairly easy going, and also quick to forgive. The number one way to offend me is to do or say something to disagree with my fundamental belief that all human beings have worth.
.SS "Q: Did you really write an man about-me page?"
You're reading it, aren't you?
.SH BUGS
Prefers boring technology, can be committed to the point of stubbornness. Likes puns.
.SH AUTHOR
Wayne Werner <wayne+gh@waynewerner.com>
.SH "SEE ALSO"
.BR gopher://gopher.waynewerner.com,
.BR https://www.waynewerner.com,
.BR https://vsre.info/
